In [1]:
!pip3 install numpy


  Using cached numpy-2.3.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.3.1-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)


In [2]:
import numpy as np
import sys

intializing Array

In [16]:
a = np.array([1,2,3] , dtype = 'int16') #one dimensional array
print(a)

[1 2 3]


In [ ]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]]) #2-D array of floats
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


how do we get the dimension of our numpy array?

In [ ]:
a.ndim #get dimension

1

In [ ]:
b.ndim #get dimension

2

how do we get shape of an array

In [ ]:
a.shape #get shape

(3,)

In [ ]:
b.shape # get shape

(2, 3)

if we want to know how much memory it take

In [17]:
#get dtype
a.dtype

dtype('int16')

In [14]:
#get dtype
b.dtype

dtype('float64')

item size

In [26]:
print(a.itemsize)
print(b.itemsize)

2
8


In [27]:
# get total no. of elementb aur size of array
print(a.size)
print(b.size)


3
6


In [28]:
#total size
print(a.nbytes) #or
print(a.itemsize*a.size)
print(b.nbytes) #or
print(b.itemsize*a.size)


6
6
48
24


Accessing/changing specific element , rows, column, etc

In [66]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [67]:
#get a specific element [row,column] # range of row: 0-1 column: 0-6
print(a[1,4])

12


In [68]:
print(a[1,-2]) #from the back

13


In [ ]:
#get a specific row
print(a[0, :])

[1 2 3 4 5 6 7]


In [44]:
#get a specific column
print(a[:,3])

[ 4 11]


In [72]:
#getting little more fancy [startindex:endindex:stepsize]
a[0, 1:-1:2]

array([2, 4, 6])

In [73]:
#chanining the specific element
a[1,4]=15
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 15 13 14]]


In [ ]:
#chainging the series of elements in row
a[0, 1:5]=[16,17,18,19]
print(a)

[[ 1 16 17 18 19  6  7]
 [ 8  9 10 11 15 13 14]]


In [81]:
##chainging the series of elements in column
a[:,2] = [20,21]
print(a)

[[ 1 16 20 18 19  6  7]
 [ 8  9 21 11 15 13 14]]


3D examples


In [93]:
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [ ]:
#get specific element in 3 dimensional array
print(c[0,1,1])

4


In [96]:
print(c[1,:,:])

[[5 6]
 [7 8]]


In [97]:
print(c[:,1,:])

[[3 4]
 [7 8]]


In [98]:
print(c[:,:,1])

[[2 4]
 [6 8]]


In [102]:
#replace
c[:,1,:]=[[9,8],[10,11]]
print(c)

[[[ 1  2]
  [ 9  8]]

 [[ 5  6]
  [10 11]]]


Initializing different type of arrays

In [104]:
 #all zeros matices
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [107]:
 #all zeros matices
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [115]:
np.ones((2,3), dtype = 'int16') #all one matrices


array([[1, 1, 1],
       [1, 1, 1]], dtype=int16)

In [117]:
#any other number
np.full((2,2),99 , dtype = 'int16')

array([[99, 99],
       [99, 99]], dtype=int16)

In [ ]:
#any other number (full-like)
c = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
np.full(c.shape, 45)

array([[[45, 45],
        [45, 45]],

       [[45, 45],
        [45, 45]]])

In [124]:
# initializing the matriz of random decimal number
np.random.rand(2,3)

array([[0.19497775, 0.16049651, 0.45340845],
       [0.52109599, 0.55664658, 0.5760716 ]])

In [125]:
np.random.random_sample(c.shape)

array([[[0.20116979, 0.85462625],
        [0.4888585 , 0.57449146]],

       [[0.90725059, 0.31985485],
        [0.55155797, 0.375425  ]]])

In [168]:
#random integer value
np.random.randint(-100,100, size=(4,4)) #first&second argument is range like -100-99

array([[-12, -28,  36, -72],
       [  6,  59,  29, -66],
       [-27,  78,  62,  95],
       [-84,  30, -71,   9]])

In [169]:
#identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#repeat an array
arr = np.array([1,2,3])
r1 = np.repeat(arr,3)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [ ]:
#repreat an array
arr = np.array([[1,2,3]]) #2D
r1 = np.repeat(arr,3, axis=0 )
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [ ]:
output = np.ones((5,5), dtype='int64')
z = np.zeros((3,3), dtype='int64')
z[1,1] = 9
output[1:4,1:4] = z #or output[1:-1,1:-1] = z 
print(output)


[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### Be Careful while copying arrays!!!

In [28]:
a=np.array([1,2,3])
print(a)
b=a
b[0]=100
print(a)
print(b)


[1 2 3]
[100   2   3]
[100   2   3]


To prevent that use copy function

In [30]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(a)
print(b)


[1 2 3]
[100   2   3]


### MATHEMATICS

In [ ]:
a=np.array([1,2,3,4])
print(a)
print(a*2)
print(a+2)
print(a-2)
print(a/2)


[1 2 3 4]
[2 4 6 8]
[3 4 5 6]
[-1  0  1  2]
[0.5 1.  1.5 2. ]


In [35]:
b = np.array([1,2,1,2])
print(a+b)

[2 4 4 6]


In [36]:
print(a**2)

[ 1  4  9 16]


In [ ]:
#take the sin 
a=np.array([1,2,3,4])
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [38]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

#### Linear alegbra

In [47]:
#multiplication of two matrix
a=np.full((2,3),2)
print(a)
b=np.full((3,2),3)
print(b)
np.matmul(a,b)

[[2 2 2]
 [2 2 2]]
[[3 3]
 [3 3]
 [3 3]]


array([[18, 18],
       [18, 18]])

In [ ]:
#determinant of the matrix
c = np.identity(3)
det = np.linalg.det(c)
print(det)

1.0


#### Statistics

In [ ]:
#minimum value in array
stats = np.array([[1,2,3],[4,5,6]])
np.min(stats)

np.int64(1)

In [ ]:
#maximum value in array
np.max(stats,)

array([3, 6])

In [ ]:
#row basis
np.min(stats, axis=1)

array([1, 2, 3])

In [ ]:
#sum of all elements
np.sum(stats)

np.int64(21)

In [63]:
#sum of all elements of column
np.sum(stats, axis=0)

array([5, 7, 9])

In [64]:
#sum of all elements of row
np.sum(stats, axis=1)

array([ 6, 15])

#### Reorganizing array

In [ ]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
print(before.shape)

after =before.reshape((4,2))
print(after)
after =before.reshape((8,1))
print(after)
after =before.reshape((1,8))
print(after)
#3D
after =before.reshape((2,2,2))
print(after)
print(after.shape)

[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]
[[1 2 3 4 5 6 7 8]]
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)


In [80]:
#vertically stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.vstack([v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
#horizontal stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.hstack([v1,v2,v1])

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

In [90]:
#horizontal stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])

np.hstack((v1,v2,v1))

array([1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

In [ ]:
#horizontal stacking vectors
v1=np.ones([2,3])
v2=np.zeros([2,2])

np.hstack([v1,v2])

array([[1., 1., 1., 0., 0.],
       [1., 1., 1., 0., 0.]])

#### Load Data From File

In [ ]:
filedata = np.genfromtxt('data.txt' , delimiter=',' ,dtype='int64')
print(filedata)

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


### Advanced Indexing and Boolean Masking

In [97]:
#where is filedata the value is greater then 50
filedata>50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [98]:
#index
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88])

you can index with a list in numpy

In [99]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])