In [1]:
!pip3 install numpy


  Using cached numpy-2.3.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.3.1-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)


In [2]:
import numpy as np
import sys

intializing Array

In [16]:
a = np.array([1,2,3] , dtype = 'int16') #one dimensional array
print(a)

[1 2 3]


In [ ]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]]) #2-D array of floats
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


how do we get the dimension of our numpy array?

In [ ]:
a.ndim #get dimension

1

In [ ]:
b.ndim #get dimension

2

how do we get shape of an array

In [ ]:
a.shape #get shape

(3,)

In [ ]:
b.shape # get shape

(2, 3)

if we want to know how much memory it take

In [17]:
#get dtype
a.dtype

dtype('int16')

In [14]:
#get dtype
b.dtype

dtype('float64')

item size

In [26]:
print(a.itemsize)
print(b.itemsize)

2
8


In [27]:
# get total no. of elementb aur size of array
print(a.size)
print(b.size)


3
6


In [28]:
#total size
print(a.nbytes) #or
print(a.itemsize*a.size)
print(b.nbytes) #or
print(b.itemsize*a.size)


6
6
48
24


Accessing/changing specific element , rows, column, etc

In [30]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
#get a specific element [row,column] # range of row: 0,1 column: 0-6
print(a[1,4])

13


In [ ]:
print(a[1,-2]) #from the back

13


In [ ]:
#get a specific row
print(a[0, :])

[1 2 3 4 5 6 7]


In [43]:
#get a specific column
print(a[:,3])

[ 4 11]


In [ ]:
#getting little more fancy


In [36]:
#chanining the specific element
a[1,4]=15
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 15 13 14]]
