In [1]:
!pip3 install numpy


  Using cached numpy-2.3.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Using cached numpy-2.3.1-cp313-cp313-macosx_14_0_arm64.whl (5.1 MB)


In [2]:
import numpy as np
import sys

intializing Array

In [ ]:
a = np.array([1,2,3]) #one dimensional array
print(a)

array([1, 2, 3])

In [ ]:
b = np.array([[1.0,2.0,3.0],[4.0,5.0,6.0]]) #2-D array of floats
print(b)

[[1. 2. 3.]
 [4. 5. 6.]]


how do we get the dimension of our numpy array?

In [ ]:
a.ndim #get dimension

1

In [ ]:
b.ndim #get dimension

2